[package]
cjc-version = "1.1.0"
name = "yjson"
organization = ""
description = "High-performance generated JSON library for Cangjie"
version = "0.1.0"
target-dir = ""
output-type = "static"
compile-option = "-O2"
override-compile-option = ""
link-option = ""
package-configuration = {}

[dependencies]

[test-dependencies]
yjson_macros = { git = "https://github.com/lIlIIlIll/yjson_macros.git", commitId = "30c3def793054c4b5ba25be2e22598e141923a51" }

[profile.bench]
no-color = true
verbose = true

[profile.bench.build]
compile-option = "-O2"
link-option = ""
