[package]
cjc-version = "1.1.0"
name = "yjson_backend_benchmarks"
organization = ""
description = "Semantic DOM backend benchmarks for yjson"
version = "0.1.0"
target-dir = ""
script-dir = ""
output-type = "executable"
compile-option = "-O2"
override-compile-option = ""
link-option = ""
package-configuration = {}

[dependencies]
yjson = { path = "../..", output-type = "static" }
yjson_native = { path = "../yjson_native" }
yjson_yyjson = { path = "../yjson_yyjson" }
