[package]
cjc-version = "1.1.0"
name = "yjson_native_accel"
description = "Single-option startup acceleration for yjson"
version = "0.1.0"
output-type = "static"
compile-option = "-O2"
link-option = "-L target/native -lyjson_scanner"

[dependencies]
yjson_native_primitives = "0.1.0"
