[package]
cjc-version = "1.1.0"
name = "yjson_native_primitives"
description = "Closed Linux x86_64 native primitive SPI for yjson"
version = "0.1.0"
script-dir = ""
output-type = "dynamic"
compile-option = "-O2"
link-option = "-L target/native -lyjson_scanner"

[dependencies]
yjson = "0.1.0"
