[package]
cjc-version = "1.1.0"
name = "yjson_native_accel"
description = "Single-option startup acceleration for yjson"
version = "2.0.0"
output-type = "static"

[dependencies]
yjson = "2.0.0"
yjson_native = "2.0.0"
