[package]
cjc-version = "1.1.0"
name = "yjson_benchmarks"
organization = ""
description = "Benchmarks for yjson"
version = "2.0.0"
target-dir = ""
script-dir = ""
output-type = "executable"
compile-option = "-O2"
override-compile-option = ""
link-option = "-L target/native -lyjson_scanner -lstdx.encoding.jsonFFI -lstdx.encoding.json.streamFFI"
package-configuration = {}

[dependencies]
  "yjson" = { path = "../..", output-type = "static" }
  "yjson_all" = { path = "../yjson_all" }
  "stdx" = "0.0.3"
