schema_version = 3
status = "qualified"
distribution = "source"
platform = "linux-x86_64"

version = "0.7.2"
version_output = "cjdoc 0.7.2"
version_args = ["--version"]

source_url = "https://github.com/lIlIIlIll/cjdoc/tree/fe0b5a5294c6d98dc1e6fb7d6d41cb5e9b04d4c0"
source_archive_url = "https://github.com/lIlIIlIll/cjdoc/archive/fe0b5a5294c6d98dc1e6fb7d6d41cb5e9b04d4c0.tar.gz"
source_archive_sha256 = "06e07cad8052cfbc4464fbc6ec27c393447b38bb2688741ce0a096b525401f75"
source_revision = "fe0b5a5294c6d98dc1e6fb7d6d41cb5e9b04d4c0"
source_directory = "cjdoc-fe0b5a5294c6d98dc1e6fb7d6d41cb5e9b04d4c0"
binary_path = "target/release/bin/main"
build_command = ["cjpm", "build"]

cjc_channel = "nightly"

license_spdx = "MIT"
license_url = "https://github.com/lIlIIlIll/cjdoc/blob/fe0b5a5294c6d98dc1e6fb7d6d41cb5e9b04d4c0/LICENSE"
manual_url = "https://github.com/lIlIIlIll/cjdoc/blob/fe0b5a5294c6d98dc1e6fb7d6d41cb5e9b04d4c0/README.md"
