schema_version = 3
status = "qualified"
distribution = "source"
platform = "linux-x86_64"

version = "0.7.2"
version_output = "cjdoc 0.7.2"
version_args = ["--version"]

source_url = "https://github.com/lIlIIlIll/cjdoc/tree/fe0b5a5294c6d98dc1e6fb7d6d41cb5e9b04d4c0"
source_archive_url = "https://github.com/lIlIIlIll/cjdoc/archive/refs/tags/v0.7.2.tar.gz"
source_archive_sha256 = "4e935d856b07afebc709a4d800c99196f4ca08a05ea9235734ebbd7e35a0cb70"
source_revision = "fe0b5a5294c6d98dc1e6fb7d6d41cb5e9b04d4c0"
source_directory = "cjdoc-fe0b5a5294c6d98dc1e6fb7d6d41cb5e9b04d4c0"
binary_path = "target/release/bin/main"
build_command = ["cjpm", "build"]

cjc_channel = "nightly"

license_spdx = "MIT"
license_url = "https://github.com/lIlIIlIll/cjdoc/blob/fe0b5a5294c6d98dc1e6fb7d6d41cb5e9b04d4c0/LICENSE"
manual_url = "https://github.com/lIlIIlIll/cjdoc/blob/fe0b5a5294c6d98dc1e6fb7d6d41cb5e9b04d4c0/README.md"
