[package]
  cjc-version = "1.1.0"
  name = "yjson_native"
  organization = ""
  description = "Optional Linux x86_64 native facade for yjson"
  version = "1.0.0"
  target-dir = ""
  script-dir = ""
  output-type = "dynamic"
  compile-option = "-O2"
  override-compile-option = ""
  link-option = "-L target/native -lyjson_scanner"
  package-configuration = {}

[dependencies]
  yjson = { path = "../.." }
