#!/usr/bin/env python3
"""Generate the readable Stream workload reference from protocol artifacts."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "benchmarks" / "stream_protocol" / "workloads.json"
DEFAULT_OUTPUT = ROOT / "docs" / "performance" / "stream-workloads.md"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def payload_card(item: dict[str, object], artifact_dir: Path, metadata: dict[str, object]) -> list[str]:
    payload_id = str(item["id"])
    path = artifact_dir / f"{payload_id}.json"
    raw = path.read_bytes()
    parsed = json.loads(raw)
    recorded = metadata["payloads"][payload_id]
    if recorded != {"bytes": len(raw), "sha256": digest(path)}:
        raise ValueError(f"payload identity drift for {payload_id}")
    lines = [
        f"## `{payload_id}`",
        "",
        f"- 类型：`{item['type']}`",
        f"- 实际 UTF-8 大小：`{len(raw):,}` bytes",
        f"- SHA-256：`{digest(path)}`",
        f"- 生成参数：`record_count={item['record_count']}`",
        "- API：decode 使用 `YJson.fromJson<T>(stream)`；encode 使用 `YJson.writeJson(value, output)`。",
        "",
    ]
    if payload_id == "person":
        lines.extend(["完整 JSON：", "", "```json", json.dumps(parsed, ensure_ascii=False, indent=2), "```", ""])
    else:
        lines.extend([
            "结构：顶层是 `ProfileRecord` 数组。下面列出首尾元素；完整 payload 保存在结果 artifact。",
            "",
            "首元素：", "", "```json", json.dumps(parsed[0], ensure_ascii=False, indent=2), "```", "",
            "尾元素：", "", "```json", json.dumps(parsed[-1], ensure_ascii=False, indent=2), "```", "",
        ])
    return lines


def generate(result_root: Path) -> str:
    spec = json.loads(SPEC.read_text(encoding="utf-8"))
    metadata = json.loads((result_root / "metadata.json").read_text(encoding="utf-8"))
    if spec["protocol_version"] != metadata["protocol_version"]:
        raise ValueError("Stream protocol version mismatch")
    artifact_dir = result_root / "payloads"
    lines = [
        "# Stream workload 参考",
        "",
        "<!-- Generated by scripts/generate_json_stream_workloads.py. Do not edit factual fields. -->",
        "",
        "本页把性能表里的 payload 展开成人可以检查的输入。大小和 SHA-256 来自正式运行导出的",
        "JSON artifact，不是手工估算。测量边界和统计规则见[Stream 性能](stream.md)。",
        "",
    ]
    for item in spec["payloads"]:
        lines.extend(payload_card(item, artifact_dir, metadata))
    lines.extend([
        "## 输入与输出 profile",
        "",
        "Decode chunk profile：",
        "",
    ])
    for item in spec["decode_chunks"]:
        lines.append(f"- `{item['id']}`：{item['description']}。")
    lines.extend(["", "Encode sink profile：", ""])
    for item in spec["encode_sinks"]:
        lines.append(f"- `{item['id']}`：{item['description']}。")
    lines.extend([
        "",
        "protocol v1 artifact 的生命周期分别是 `Unpooled one-shot` 与 `Pooled steady-state`。",
        "两者都调用相同 public API；前者通过 benchmark 环境开关关闭实验池。实验结果未达到",
        "生命周期门槛，因此当前产品实现不包含该池。",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("result_root", type=Path)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generate(args.result_root)
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != content:
            raise SystemExit(f"generated Stream workload documentation is stale: {args.output}")
        print("Stream workload documentation is current")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
