[package]
cjc-version = "1.1.0"
name = "yjson_native_accel_benchmarks"
organization = ""
description = "Pure and Native single-engine qualification benchmarks for yjson"
version = "0.1.0"
output-type = "executable"
compile-option = "-O2"

[dependencies]
  yjson = { path = "../..", output-type = "static" }
  yjson_native_accel = { path = "../yjson_native_accel", output-type = "static" }
